---
title: "Analyzing America's War Zone"
author: "Frequentists in the Sheets"
header-includes:
   - \usepackage{url}
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Introduction

\noindent When one thinks of crime in America, Chicago is a city that often comes to mind. Donald Trump frequently discusses the issues of crime in Chicago. According to the Chicago Tribune, there were 4,367 shooting victims in Chicago in 2016. In the same year there were also 785 homicides.\footnote{Rick Pearson, "Trump Again Assails Chicago gun violence in speech to Congress", \textit{Chicago Tribune}, \url{http://www.chicagotribune.com/news/local/politics/ct-donald-trump-congress-speech-chicago-met-20170228-story.html}, March 2017.} However, other reports cite that Chicago should not be called the “crime capital” of America. It’s violent rate is less than other cities such as St.  Louis and Detroit. \foonote{Andrew V. Papachristos, "48 Years of Crime in Chicago: An Analysis of of Serious Crime Trends from 1965-2013,\url{http://isps.yale.edu/sites/default/files/publication/2013/12/48yearsofcrime_final_ispsworkingpaper023.pdf}, December 2013.} This project examines crime in Chicago, specifically armed robberies, from 2011-2017. \newline

#Data

\noindent The crime data used for this project comes from the City of Chicago’s website. \footnote{Crimes 2001 to present, \url{https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2/data}} The data contains every reported crime in Chicago from 2001 to present day. In addition to the type of crime reported (battery, assault, etc.), there is information on the location, time, and other details. The data set was reduced to only armed robberies. 
b.	Years 2002-2016 there is at least armed robbery every day
